// app/models/PetModel.js
import mongoose from "mongoose";

const petSchema = new mongoose.Schema({
  name: String,
  type: String,
  age: Number,
  breed: String,
  gender: { type: String, enum: ['Male', 'Female'], required: true },
  
  temperament: { 
    type: String, 
    enum: ['Calm', 'Playful', 'Shy', 'Friendly', 'Energetic', 'Independent', 'Curious', 'Other'], 
    default: 'Friendly' // <-- Keep default for pets made before this change
  },
  energyLevel: { 
    type: String, 
    enum: ['Low', 'Medium', 'High'], 
    default: 'Medium' // <-- Keep default
  },
  listingType: {
    type: String,
    enum: ['Mating', 'Adoption'],
    default: 'Mating',
    required: true
  },
  
  // --- Pedigree Fields ---
  damId: { type: mongoose.Schema.Types.ObjectId, ref: 'Pet', default: null },
  sireId: { type: mongoose.Schema.Types.ObjectId, ref: 'Pet', default: null },
  
  // --- Blockchain Fields ---
  nftTokenId: { type: Number, default: null, index: true },
  nftContractAddress: { type: String, default: null },

  certificateUrl: String,
  imageUrls: [String],
  ownerId: String,
  
  isPregnant: { type: Boolean, default: false },

  verificationStatus: { 
    type: String, 
    enum: ['pending', 'verified', 'rejected', 'needs-review'],
    default: 'pending' 
  },
  
  verificationAnalysis: {
    ocrText: { type: String, default: null },
    aiResponse: { type: String, default: null },
    aiStatus: { type: String, default: 'pending' }, 
  },

  // --- NEW: AI Generated Profile String ---
  // This string will be generated by the questionnaire
  aiProfileString: { type: String, default: null, index: true },
  // --- END NEW ---
  
  isBanned: { type: Boolean, default: false },

  matingHistory: [
    // ... (your existing matingHistory schema)
  ],
  
  messages: [
    // ... (your existing messages schema)
  ],
  
  adoptionRequests: [
    // ... (your existing adoptionRequests schema)
  ]
});

petSchema.index({ location: '2dsphere' });

const Pet = mongoose.models.Pet || mongoose.model("Pet", petSchema);
export default Pet;